# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'game_drink.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import random
import base
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        MainWindow.setStyleSheet("background-color: rgb(255, 84, 84);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.quastion = QtWidgets.QLabel(self.centralwidget)
        self.quastion.setGeometry(QtCore.QRect(40, 60, 700, 400))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quastion.sizePolicy().hasHeightForWidth())
        self.quastion.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.quastion.setFont(font)
        self.quastion.setMouseTracking(False)
        self.quastion.setStyleSheet("color: rgb(255, 255, 255);\n"
                                    "word-wrap: break-word;\n"
                                    "padding: 2px;\n"
                                    "margin: 5px;")
        self.quastion.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.quastion.setFrameShadow(QtWidgets.QFrame.Plain)
        self.quastion.setScaledContents(False)
        self.quastion.setAlignment(QtCore.Qt.AlignCenter)
        self.quastion.setWordWrap(True)
        self.quastion.setIndent(1)
        self.quastion.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.quastion.setObjectName("quastion")
        self.pushButton_next = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_next.setGeometry(QtCore.QRect(260, 500, 301, 61))
        self.pushButton_next.setSizeIncrement(QtCore.QSize(800, 600))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_next.setFont(font)
        self.pushButton_next.setStyleSheet("color: rgb(255, 255, 255);\n"
                                           "background-color: rgb(0, 0, 0);\n"
                                           "border-radius:10px;")
        self.pushButton_next.setObjectName("pushButton_next")

        font = QtGui.QFont()
        font.setPointSize(20)

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.next_button()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ВОПРОС-ОТВЕТ"))
        self.quastion.setText(_translate("MainWindow", "вопросы"))
        self.pushButton_next.setText(_translate("MainWindow", "Далее"))

    def next_button(self):
        array = []
        ques = open('question.txt', 'r', encoding='UTF-8')
        for i in ques:
            array.append(i)
        self.pushButton_next.clicked.connect(lambda: self.next_question(Question=random.choice(array)))

    def next_question(self, Question):
        self.quastion.setText(Question)

    def pars_question(self):
        ques = open('question.text')
        ques.read()


if __name__ == '__main__':
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
